### ISSUE TITLE
depsyncer error: 400 Bad Request: USER_AGENT_INVALID

### ISSUE THREAD

**Issue by guixiaomin** [micromdm/nanodep#42]
[root@iZuf64hzarhamgerishd1nZ nanodep]# ./depsyncer-linux-amd64 -debug -limit 1000 -duration 60 dep
2024/01/22 00:55:28 level=debug component=syncer name=dep msg=starting timer duration=1m0s
2024/01/22 00:55:29 level=info component=syncer name=dep msg=error syncing phase=fetch cursor= err=DEP HTTP error: 400 Bad Request: USER_AGENT_INVALID
2024/01/22 00:56:29 level=info component=syncer name=dep msg=error syncing phase=fetch cursor= err=DEP HTTP error: 400 Bad Request: USER_AGENT_INVALID

As a beginner, I am using nanodep, and according to the reference documentation, I have made the settings, but I encountered a problem when enabling depsyncer. Please help me, thank you.

**Comment by jessepeterson** [comment]
@guixiaomin hmm, I've never seen the `USER_AGENT_INVALID`, that's interesting. do any other calls work? can you use the DEP api endpoints otherwise?

**Comment by guixiaomin** [comment]
Thank you. The DEP endpoint is functioning properly as a proxy, and I am currently using dep-assign-profile.sh.
I will monitor this issue later

**Comment by JieAnthony** [comment]
I also have the same error. 
```log
2024/02/15 17:22:35 level=debug component=syncer name=mdmserver1 msg=starting timer duration=5s
2024/02/15 17:22:35 level=info component=syncer name=mdmserver1 msg=error syncing phase=fetch cursor= err=DEP HTTP error: 400 Bad Request: USER_AGENT_INVALID
2024/02/15 17:22:40 level=info component=syncer name=mdmserver1 msg=error syncing phase=fetch cursor= err=DEP HTTP error: 400 Bad Request: USER_AGENT_INVALID
```
My API to get account details works fine
```log
/proxy/{dep_name}/account
```
Please tell me how to troubleshoot the `USER_AGENT_INVALID` error

**Comment by JieAnthony** [comment]
@jessepeterson

**Comment by jessepeterson** [comment]
Let me take a look at all this. @JieAnthony the second (last) comment makes me think the DEP name is incorrect — it can't find any tokens based on that.

**Comment by JieAnthony** [comment]
I'm sorry, my English is not very good. I will start from the beginning and explain the problem to you again.

nanoDEP start command
```shell
// it works fine
./depserver-linux-amd64 -api supersecret -listen :7592 -storage mysql -storage-dsn "root:root@tcp(127.0.01:3306)/nanodep"
```
When I access /server/devices through the proxy, everything works fine.
```json
{
    "devices": [],
    "fetched_until": "2024-02-15T09:37:05Z",
    "more_to_follow": false,
    "cursor": "MDowOjE3MDc5ODk4MjU3NzY6MTcwNzk4OTgyNTc3Njp0cnVlOjE3MDc5ODk4MjU3NzY"
}
```

depsyncer start command
```shell
./depsyncer-linux-amd64 -storage "mysql" -storage-dsn "root:root@tcp(127.0.0.1:3306)/nanodep" -debug -debug-assigner -debug-syncer mdmserver1
```
RESULT
```log
2024/02/17 10:43:17 level=debug component=syncer name=mdmserver1 msg=starting timer duration=30m0s
2024/02/17 10:43:18 level=info component=syncer name=mdmserver1 msg=error syncing phase=fetch cursor= err=DEP HTTP error: 400 Bad Request: USER_AGENT_INVALID
```
![WechatIMG69282](https://github.com/micromdm/nanodep/assets/38497992/40ffb772-c43d-45ea-933d-e25855767362)

I have a **mdmserver1**

**Comment by JieAnthony** [comment]
@jessepeterson hi,Could you please tell me how to fix this problem? Or my operation is wrong?

**Comment by jessepeterson** [comment]
Hello! I've been able to reproduce this issue. If I indeed change the `User-Agent` header here:

https://github.com/micromdm/nanodep/blob/e87b1e3f2b459aeced39d6f873ae15ca9caf552b/godep/client.go#L18

.. to something else then it works fine. I suspect this is an Apple server-side issue. Let me do some asking around.

**Comment by JieAnthony** [comment]
Thank you for your great work.
I have a request and hope you can accept it.
I hope to have one more option in `depsyncer`, such as `-all-dep` to indicate synchronization of all `dep`.
Because I may have many `dep`, it may not be convenient if I have to restart every time I add a new one.
@jessepeterson

**Comment by jessepeterson** [comment]
@JieAnthony 

> I have a request and hope you can accept it.

Hi! Yeah this is interesting. We don't currently have a way to enumerate/search for for existing DEP names therefore don't have a way to know what "all" DEP names are. :)

But if you'd like to see this: please make a feature request new issue (this one is just about the 400 user agent issue).

**Comment by JieAnthony** [comment]
@jessepeterson 
I feel so sorry.
Your work is great.

**Comment by Gaoxichao** [comment]
I also have the same error. @jessepeterson

**Comment by jessepeterson** [comment]
I'm not sure _why_ Apple is blocking our user-agent string, but they are. #49 changes it to something slightly different.

**Comment by jessepeterson** [comment]
There are new [binaries from CI/CD](https://github.com/micromdm/nanodep/actions/runs/8269487115) and Docker images pushed here if you want to test out these changes.
