### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by JieAnthony** [micromdm/nanodep#56]
[#42](https://github.com/micromdm/nanodep/issues/42)The issue appears to be working correctly.
Can you release the latest version?
@jessepeterson

**Comment by jessepeterson** [comment]
Hello @JieAnthony. I'll see what I can do this coming week. No promises though.

**Comment by JieAnthony** [comment]
@jessepeterson Thank you for your great work!

**Comment by jessepeterson** [comment]
Hello @JieAnthony, released [v0.4.0](https://github.com/micromdm/nanodep/releases/tag/v0.4.0)
