### ISSUE TITLE
[BUG]depsyncer callback error dep_name

### ISSUE THREAD

**Issue by JieAnthony** [micromdm/nanodep#69]
When multiple `DEPNAME` are configured, the device_response_event.dep_name in the callback data is always the last one.

example

```shell
./nanodep/depsyncer-linux-amd64 -webhook-url "http://webhook" -storage mysql -storage-dsn "root:root@tcp(host:3306)/nanodep" -limit 100 -duration 600 foo bar
```
device_response_event.dep_name in the callback is always bar

**Comment by JieAnthony** [comment]
@jessepeterson

**Comment by jessepeterson** [comment]
@JieAnthony @radiohertz can you verify that 615551d0d38975509840e813efcaadca42692511 fixes the issue?

**Comment by JieAnthony** [comment]
@jessepeterson fixed! Thank you!!!

**Comment by JieAnthony** [comment]
Thank @jessepeterson @radiohertz
Is it possible to release a latest version for this fix?
